---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: ${aws-provider-name}
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-aws:${coalesce(provider-aws-version, "v0.33.0")}
  controllerConfigRef:
    name: aws-controller-config
